name: Resto CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  GITHUB_TOKEN: ${{ github.token }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  bfs: # build from source
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Building From Source
      run: |
        go mod tidy
        go run ./build/date.go >> date.txt
        go build -ldflags "-X main.version=$(git describe --abbrev=0 --tags) -X main.versionDate=$(cat date.txt)" -o resto

    - name: Run `Restofile`
      run: |
        ./resto run ./examples/restofile/basic_request/Restofile

  bfs_windows: # build from source (windows)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Building From Source
      run: |
        .\scripts\bfs.ps1
        echo "::add-path::C:\Users\runneradmin\AppData\Local\resto\bin\;"

    - name: Test it
      run: resto run -f ./examples/restofile/basic_request/RestoFile

  from_script:
    needs: [ bfs ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install from script
      run: curl -sL https://git.io/resto | bash

    - name: Test it
      run: resto get https://api.github.com/gitignore/templates/Go

  from_script_windows:
    needs: [ bfs_windows ]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install from script
      run: |
        iwr -useb https://git.io/resto-win | iex
        echo "::add-path::C:\Users\runneradmin\AppData\Local\resto\bin\;"

    - name: Test it
      run: resto get https://api.github.com/organizations

  go:
    needs: [ bfs, bfs_windows ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install from Go
      run: go install github.com/abdfnx/resto@latest

    - name: Install `deno` from resto
      run: |
        resto install https://deno.land/x/install/install.sh
        export DENO_INSTALL="/home/runner/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"

        deno -V
        deno run https://deno.land/std/examples/welcome.ts

  from_gh_cli:
    needs: [ bfs, bfs_windows, go ]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install from script
      run: gh extension install abdfnx/gh-resto

    - name: Test it
      run: |
        gh resto get https://api.secman.dev
        cat examples/spacex.gql | gh resto post https://api.spacex.land/graphql -c graphql --body-stdin
